/// Data access for the upay Shadhin app.
///
/// The app runs in one of two modes:
///
/// **live** - talks to the FastAPI service. This is what you get running locally, and
/// it is the architecture the product would ship with.
///
/// **precomputed** - reads a bundle of JSON generated by `deploy/precompute.py`. The
/// published web build uses this, because hosting the ML service on a free tier would
/// hand a judge a one-minute cold start on their first click. Every figure in the
/// bundle is still real model output from the same `api/service.py` code path; it was
/// just computed ahead of time.
///
/// Which mode is running is always stated in the UI. Serving precomputed data while
/// implying it is live would be dishonest, and the distinction matters: in precomputed
/// mode the numbers are fixed to one forecast date.
library;

import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;
import 'package:http/http.dart' as http;

const String kDefaultBaseUrl = String.fromEnvironment(
  'SHADHIN_API_BASE_URL',
  defaultValue: 'http://127.0.0.1:8000',
);

/// Set at build time for the published web bundle:
/// `flutter build web --dart-define=SHADHIN_STATIC=true`
const bool kStaticBuild = bool.fromEnvironment('SHADHIN_STATIC');

enum DataMode { live, precomputed }

class ApiClient extends ChangeNotifier {
  ApiClient({this.baseUrl = kDefaultBaseUrl});

  final String baseUrl;

  DataMode _mode = kStaticBuild ? DataMode.precomputed : DataMode.live;
  DataMode get mode => _mode;
  bool get isPrecomputed => _mode == DataMode.precomputed;

  final Map<String, Map<String, dynamic>> _bundles = {};
  Map<String, dynamic>? _manifest;

  void _setMode(DataMode m) {
    _mode = m;
    notifyListeners();
  }

  // --- precomputed bundle -------------------------------------------------

  Future<Map<String, dynamic>> _loadManifest() async {
    return _manifest ??= jsonDecode(
      await rootBundle.loadString('assets/demo/manifest.json'),
    ) as Map<String, dynamic>;
  }

  Future<Map<String, dynamic>> _loadBundle(String id) async {
    return _bundles[id] ??= jsonDecode(
      await rootBundle.loadString('assets/demo/$id.json'),
    ) as Map<String, dynamic>;
  }

  /// The forecast date the precomputed bundle was generated for.
  Future<String> precomputedAsOf() async =>
      (await _loadManifest())['as_of'] as String? ?? '';

  // --- requests -----------------------------------------------------------

  /// Try the live API; on any failure fall back to the precomputed bundle.
  Future<Map<String, dynamic>?> _tryGet(String path) async {
    if (kStaticBuild) return null;
    try {
      final r = await http
          .get(Uri.parse('$baseUrl$path'))
          .timeout(const Duration(seconds: 4));
      if (r.statusCode == 200) {
        _setMode(DataMode.live);
        return jsonDecode(utf8.decode(r.bodyBytes)) as Map<String, dynamic>;
      }
    } catch (_) {
      // fall through to the bundle
    }
    _setMode(DataMode.precomputed);
    return null;
  }

  Future<List<dynamic>> users() async {
    if (!kStaticBuild) {
      try {
        final r = await http
            .get(Uri.parse('$baseUrl/users?limit=12'))
            .timeout(const Duration(seconds: 4));
        if (r.statusCode == 200) {
          _setMode(DataMode.live);
          return jsonDecode(utf8.decode(r.bodyBytes)) as List<dynamic>;
        }
      } catch (_) {
        // fall through
      }
    }
    _setMode(DataMode.precomputed);
    return (await _loadManifest())['users'] as List<dynamic>;
  }

  Future<Map<String, dynamic>> profile(String id) async =>
      await _tryGet('/profile/$id') ??
      (await _loadBundle(id))['profile'] as Map<String, dynamic>;

  Future<Map<String, dynamic>> forecast(String id) async =>
      await _tryGet('/forecast/$id') ??
      (await _loadBundle(id))['forecast'] as Map<String, dynamic>;

  Future<Map<String, dynamic>> insights(String id) async =>
      await _tryGet('/insights/$id') ??
      (await _loadBundle(id))['insights'] as Map<String, dynamic>;

  Future<Map<String, dynamic>> safeToSave(String id) async =>
      await _tryGet('/safe-to-save/$id') ??
      (await _loadBundle(id))['safe_to_save'] as Map<String, dynamic>;

  /// The first customer in the bundle, used before anything is selected.
  Future<String> defaultUserId() async {
    final list = (await _loadManifest())['users'] as List<dynamic>;
    return (list.first as Map)['user_id'] as String;
  }
}
